name: Release test

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create new pre release
        run: echo "New Release ${{ github.event.inputs.version }}"
