name: Release test

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        options: 
        - v2.2.0
        - v1.0.0

env:
  VERSION: ${{ inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create new pre release
        run: echo New Release ${{ VERSION#v }}
