name: Publish new version

on:
  push:
    tags:
      - v*
      - "!v*-alpha*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: echo Actions launched ! New version incoming
